version: "3"

services: 
  postgres:
    image: postgres
    container_name: Z_pre_test
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=inventory
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data


  api:
    build: ./API
    container_name: Inventory_API
    restart: always
    environment: 
      - DATABASE_HOST=postgres     
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=docker
      - DATABASE_PORT=5432
      - DATABASE_NAME=inventory
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  ui:
    build: ./UI
    container_name: Inventory_UI
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - api

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
